# Generated by Django 5.2.3 on 2025-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_alter_timelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='date',
            field=models.DateField(),
        ),
    ]
