# Generated by Django 5.2.3 on 2025-07-03 21:16

import timelog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_alter_timelog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='file',
            field=models.FileField(blank=True, upload_to=timelog.models.upload_filepath),
        ),
    ]
