# Generated by Django 5.2.3 on 2025-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0004_timelog_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
