# Generated by Django 5.2.3 on 2025-07-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0005_timelog_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
