# Generated by Django 5.2.3 on 2025-07-06 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exitlog', '0002_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exitlog_scraps', to='exitlog.exitlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scraps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exitlog')},
            },
        ),
        migrations.AddField(
            model_name='exitlog',
            name='scrap',
            field=models.ManyToManyField(related_name='scrap_exitlog', through='exitlog.Scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
