# Generated by Django 5.2.4 on 2025-07-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='법무법인명')),
                ('address', models.TextField(verbose_name='주소')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '법무법인',
                'verbose_name_plural': '법무법인',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='관명')),
                ('postcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '경찰서',
                'verbose_name_plural': '경찰서',
                'ordering': ['name'],
            },
        ),
    ]
